# Generated by Django 4.0.6 on 2022-07-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=20)),
                ('Verified', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
