# Generated by Django 4.0.6 on 2022-07-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='Password',
        ),
        migrations.AddField(
            model_name='signup',
            name='Verified',
            field=models.BooleanField(default=False),
        ),
    ]
