# Generated by Django 4.0.6 on 2022-07-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_app', '0002_rename_email_signup_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='token',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
    ]
