# Generated by Django 4.0.6 on 2022-07-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_app', '0004_socialapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Verified',
            field=models.CharField(default='Not Verified', max_length=20),
        ),
    ]
