# Generated by Django 4.0.6 on 2022-07-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_app', '0005_alter_signup_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Verified',
        ),
        migrations.AddField(
            model_name='signup',
            name='Verification_Status',
            field=models.CharField(default='Not Verfified', max_length=20),
        ),
    ]
