# Generated by Django 4.0.6 on 2022-07-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_app', '0006_remove_signup_verified_signup_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Verification_Status',
            field=models.CharField(default='Not Verified', max_length=20),
        ),
    ]
