# Generated by Django 4.0.6 on 2022-07-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_app', '0007_alter_signup_verification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Verification_Status',
        ),
        migrations.AddField(
            model_name='signup',
            name='Verified',
            field=models.BooleanField(default=False),
        ),
    ]
